import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/ui/custom/AppSidebar";
import { Separator } from "@radix-ui/react-separator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
              <>
            <SidebarProvider>
                <AppSidebar />
                <SidebarInset>
                    <header
                        className="flex h-16 sticky top-0 z-10 bg-primary-foreground/20 backdrop-blur-xl shrink-0 items-center
                gap-2 transition-[width,height] justify-between ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12"
                    >
                        <div className="flex items-center gap-2 px-4">
                            <SidebarTrigger className="-ml-1 size-8 text-secondary-foreground" />
                            <Separator
                                decorative
                                orientation="vertical"
                                className="data-[orientation=vertical]:h-5 text-primary"
                            />
                        </div>
                        {/* <UserDropDown className="mr-4" /> */}
                    </header>
                    {children}
                </SidebarInset>
            </SidebarProvider>
        </>
      </body>
    </html>
  );
}
